version: '2.4'

services:
  loki-example-com-app:
    image: tiredofit/loki
    labels:
      - traefik.enable=true
      - traefik.http.routers.loki-example-com.rule=Host(`loki.example.com`)
      - traefik.http.services.loki-example-com.loadbalancer.server.port=80
    container_name: loki-app
    volumes:
      - ./config:/config
      - ./data:/data
      - ./logs:/logs
      - ./logs:/www/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_ANME=loki-app

      - NGINX_AUTHENTICATION_TYPE=BASIC
      - NGINX_AUTHENTICATION_BASIC_USER1=admin
      - NGINX_AUTHENTICATION_BASIC_PASS1=admin

    networks:
      - proxy 
      - services
    restart: always


networks:
  services:
    external: true
  proxy:
    external: true
